# Generated by Django 3.2.2 on 2021-05-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_transaction_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
    ]
